Improve the error message for unknown keyword arguments
If unknown keyword arguments bubble up to object.__init__() they will
generate a rather confusing error message:

TypeError: object.__init__() takes exactly one argument (the instance to initialize)

But we can't be sure that `object` is the next __init__() in the MRO,
so we do the best we can to detect the error and to generate a useful
exception.  I'm not particularly a fan of the approach I've taken here
but I don't see any other good way that doesn't also rely on internals
that might change.

(cherry picked from commit 2d881e60449b1bb59a12a31c87bbf8aa40fce6e9)